# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Treancycle
email: trean.mi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Блог про CSS, JavaScript, Linux и прочие близкие темы.
baseurl: "" # the subpath of your site, e.g. /blog
imgurl: "/img/" # the subpath images
url: "http://www.treancycle.ru" # the base hostname & protocol for your site
twitter_username: _trean_
github_username: trean
facebook_username: mila.vasnetsova
permalink: /:/categories/:title/

# Build settings
markdown: kramdown
